import * as ImagePicker from 'react-native-image-picker';

export const validateEmail = (email: string) => {
  const re =
    /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
  return re.test(String(email).toLowerCase());
};

// async function storagePermission() {
//   const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE);
//   if (granted === PermissionsAndroid.RESULTS.GRANTED) {
//       // if get here, the user has accepted the permissions
//       launchImageLibrary()
//   } else {
//       // if get here, the user did NOT accepted the permissions
//   }
// }

export const launchImageLibrary = async () => {
  const options = {
    selectionLimit: 1,
    mediaType: 'photo',
    includeBase64: false,
  };
  try {
    const response = await ImagePicker.launchImageLibrary(options);
    if (response.didCancel) {
      console.log('User cancelled photo picker');
    } else if (response?.error) {
      console.log('ImagePicker Error: ', response?.error);
    } else {
      if (response.assets && response.assets.length) {
        return response.assets[0];
      }
    }
  } catch (error) {
    console.log('er', error);
  }
};

export const launchCamera = () => {
  let options = {
    storageOptions: {
      skipBackup: true,
      path: 'images',
    },
  };
  let imageObject = null;
  ImagePicker.launchCamera(options, (response: any) => {
    if (response.didCancel) {
      console.log('User cancelled image picker');
    } else if (response.error) {
      console.log('ImagePicker Error: ', response.error);
    } else if (response.customButton) {
      console.log('User tapped custom button: ', response.customButton);
    } else {
      console.log('response.assets[0]', response.assets[0]);

      imageObject = response.assets[0];
    }
  });
  if (imageObject) {
    return imageObject;
  }
};

export const allCountry2 = [
  {label: 'Lagos', value: 'Lagos'},
  {label: 'Kano', value: 'Kano'},
  {label: 'Ibadan', value: 'Ibadan'},
  {label: 'Port Harcourt', value: 'Port Harcourt'},
  {label: 'Benin', value: 'Benin'},
  {label: 'Kaduna', value: 'Kaduna'},
  {label: 'Abuja', value: 'Abuja'},
  {label: 'Maiduguri', value: 'Maiduguri'},
  {label: 'Zaria', value: 'Zaria'},
  {label: 'Aba', value: 'Aba'},
  {label: 'Jos', value: 'Jos'},
  {label: 'Ilorin', value: 'Ilorin'},
  {label: 'Oyo', value: 'Oyo'},
  {label: 'Enugu', value: 'Enugu'},
  {label: 'Abeokuta', value: 'Abeokuta'},
  {label: 'Sokoto', value: 'Sokoto'},
  {label: 'Onitsha', value: 'Onitsha'},
  {label: 'Warri', value: 'Warri'},
  {label: 'Ebute', value: 'Ebute'},
  {label: 'Okene', value: 'Okene'},
  {label: 'Calabar', value: 'Calabar'},
  {label: 'Uyo', value: 'Uyo'},
  {label: 'Katsina', value: 'Katsina'},
  {label: 'Ado-Ekiti', value: 'Ado-Ekiti'},
  {label: 'Akure', value: 'Akure'},
  {label: 'Lekki', value: 'Lekki'},
  {label: 'Bauchi', value: 'Bauchi'},
  {label: 'Ikeja', value: 'Ikeja'},
  {label: 'Makurdi', value: 'Makurdi'},
  {label: 'Minna', value: 'Minna'},
  {label: 'Efon-Alaaye', value: 'Efon-Alaaye'},
  {label: 'Ilesa', value: 'Ilesa'},
  {label: 'Owo', value: 'Owo'},
  {label: 'Umuahia', value: 'Umuahia'},
  {label: 'Ondo', value: 'Ondo'},
  {label: 'Ikot Ekpene', value: 'Ikot Ekpene'},
  {label: 'Iwo', value: 'Iwo'},
  {label: 'Gombe', value: 'Gombe'},
  {label: 'Jimeta', value: 'Jimeta'},
  {label: 'Atani', value: 'Atani'},
  {label: 'Gusau', value: 'Gusau'},
  {label: 'Mubi', value: 'Mubi'},
  {label: 'Ikire', value: 'Ikire'},
  {label: 'Owerri', value: 'Owerri'},
  {label: 'Shagamu', value: 'Shagamu'},
  {label: 'Ijebu-Ode', value: 'Ijebu-Ode'},
  {label: 'Ugep', value: 'Ugep'},
  {label: 'Chakwama', value: 'Chakwama'},
  {label: 'Nnewi', value: 'Nnewi'},
  {label: 'Ise-Ekiti', value: 'Ise-Ekiti'},
];

export const allCountry = [
  {label: 'Nigeria', value: 'Nigeria'},
  {label: 'Afghanistan', value: 'Afghanistan'},
  {label: 'Åland Islands', value: 'Åland Islands'},
  {label: 'Albania', value: 'Albania'},
  {label: 'Algeria', value: 'Algeria'},
  {label: 'American Samoa', value: 'American Samoa'},
  {label: 'AndorrA', value: 'AndorrA'},
  {label: 'Angola', value: 'Angola'},
  {label: 'Anguilla', value: 'Anguilla'},
  {label: 'Antarctica', value: 'Antarctica'},
  {label: 'Antigua and Barbuda', value: 'Antigua and Barbuda'},
  {label: 'Argentina', value: 'Argentina'},
  {label: 'Armenia', value: 'Armenia'},
  {label: 'Aruba', value: 'Aruba'},
  {label: 'Australia', value: 'Australia'},
  {label: 'Austria', value: 'Austria'},
  {label: 'Azerbaijan', value: 'Azerbaijan'},
  {label: 'Bahamas', value: 'Bahamas'},
  {label: 'Bahrain', value: 'Bahrain'},
  {label: 'Bangladesh', value: 'Bangladesh'},
  {label: 'Barbados', value: 'Barbados'},
  {label: 'Belarus', value: 'Belarus'},
  {label: 'Belgium', value: 'Belgium'},
  {label: 'Belize', value: 'Belize'},
  {label: 'Benin', value: 'Benin'},
  {label: 'Bermuda', value: 'Bermuda'},
  {label: 'Bhutan', value: 'Bhutan'},
  {label: 'Bolivia', value: 'Bolivia'},
  {label: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina'},
  {label: 'Botswana', value: 'Botswana'},
  {label: 'Bouvet Island', value: 'Bouvet Island'},
  {label: 'Brazil', value: 'Brazil'},
  {
    label: 'British Indian Ocean Territory',
    value: 'British Indian Ocean Territory',
  },
  {label: 'Brunei Darussalam', value: 'Brunei Darussalam'},
  {label: 'Bulgaria', value: 'Bulgaria'},
  {label: 'Burkina Faso', value: 'Burkina Faso'},
  {label: 'Burundi', value: 'Burundi'},
  {label: 'Cambodia', value: 'Cambodia'},
  {label: 'Cameroon', value: 'Cameroon'},
  {label: 'Canada', value: 'Canada'},
  {label: 'Cape Verde', value: 'Cape Verde'},
  {label: 'Cayman Islands', value: 'Cayman Islands'},
  {
    label: 'Central African Republic',
    value: 'Central African Republic',
  },
  {label: 'Chad', value: 'Chad'},
  {label: 'Chile', value: 'Chile'},
  {label: 'China', value: 'China'},
  {label: 'Christmas Island', value: 'Christmas Island'},
  {
    label: 'Cocos (Keeling) Islands',
    value: 'Cocos (Keeling) Islands',
  },
  {label: 'Colombia', value: 'Colombia'},
  {label: 'Comoros', value: 'Comoros'},
  {label: 'Congo', value: 'Congo'},
  {
    label: 'Congo, The Democratic Republic of the',
    value: 'Congo, The Democratic Republic of the',
  },
  {label: 'Cook Islands', value: 'Cook Islands'},
  {label: 'Costa Rica', value: 'Costa Rica'},
  {label: "Cote D'Ivoire", value: "Cote D'Ivoire"},
  {label: 'Croatia', value: 'Croatia'},
  {label: 'Cuba', value: 'Cuba'},
  {label: 'Cyprus', value: 'Cyprus'},
  {label: 'Czech Republic', value: 'Czech Republic'},
  {label: 'Denmark', value: 'Denmark'},
  {label: 'Djibouti', value: 'Djibouti'},
  {label: 'Dominica', value: 'Dominica'},
  {label: 'Dominican Republic', value: 'Dominican Republic'},
  {label: 'Ecuador', value: 'Ecuador'},
  {label: 'Egypt', value: 'Egypt'},
  {label: 'El Salvador', value: 'El Salvador'},
  {label: 'Equatorial Guinea', value: 'Equatorial Guinea'},
  {label: 'Eritrea', value: 'Eritrea'},
  {label: 'Estonia', value: 'Estonia'},
  {label: 'Ethiopia', value: 'Ethiopia'},
  {
    label: 'Falkland Islands (Malvinas)',
    value: 'Falkland Islands (Malvinas)',
  },
  {label: 'Faroe Islands', value: 'Faroe Islands'},
  {label: 'Fiji', value: 'Fiji'},
  {label: 'Finland', value: 'Finland'},
  {label: 'France', value: 'France'},
  {label: 'French Guiana', value: 'French Guiana'},
  {label: 'French Polynesia', value: 'French Polynesia'},
  {
    label: 'French Southern Territories',
    value: 'French Southern Territories',
  },
  {label: 'Gabon', value: 'Gabon'},
  {label: 'Gambia', value: 'Gambia'},
  {label: 'Georgia', value: 'Georgia'},
  {label: 'Germany', value: 'Germany'},
  {label: 'Ghana', value: 'Ghana'},
  {label: 'Gibraltar', value: 'Gibraltar'},
  {label: 'Greece', value: 'Greece'},
  {label: 'Greenland', value: 'Greenland'},
  {label: 'Grenada', value: 'Grenada'},
  {label: 'Guadeloupe', value: 'Guadeloupe'},
  {label: 'Guam', value: 'Guam'},
  {label: 'Guatemala', value: 'Guatemala'},
  {label: 'Guernsey', value: 'Guernsey'},
  {label: 'Guinea', value: 'Guinea'},
  {label: 'Guinea-Bissau', value: 'Guinea-Bissau'},
  {label: 'Guyana', value: 'Guyana'},
  {label: 'Haiti', value: 'Haiti'},
  {
    label: 'Heard Island and Mcdonald Islands',
    value: 'Heard Island and Mcdonald Islands',
  },
  {
    label: 'Holy See (Vatican City State)',
    value: 'Holy See (Vatican City State)',
  },
  {label: 'Honduras', value: 'Honduras'},
  {label: 'Hong Kong', value: 'Hong Kong'},
  {label: 'Hungary', value: 'Hungary'},
  {label: 'Iceland', value: 'Iceland'},
  {label: 'India', value: 'India'},
  {label: 'Indonesia', value: 'Indonesia'},
  {
    label: 'Iran, Islamic Republic Of',
    value: 'Iran, Islamic Republic Of',
  },
  {label: 'Iraq', value: 'Iraq'},
  {label: 'Ireland', value: 'Ireland'},
  {label: 'Isle of Man', value: 'Isle of Man'},
  {label: 'Israel', value: 'Israel'},
  {label: 'Italy', value: 'Italy'},
  {label: 'Jamaica', value: 'Jamaica'},
  {label: 'Japan', value: 'Japan'},
  {label: 'Jersey', value: 'Jersey'},
  {label: 'Jordan', value: 'Jordan'},
  {label: 'Kazakhstan', value: 'Kazakhstan'},
  {label: 'Kenya', value: 'Kenya'},
  {label: 'Kiribati', value: 'Kiribati'},
  {
    label: "Korea, Democratic People'S Republic of",
    value: "Korea, Democratic People'S Republic of",
  },
  {label: 'Korea, Republic of', value: 'Korea, Republic of'},
  {label: 'Kuwait', value: 'Kuwait'},
  {label: 'Kyrgyzstan', value: 'Kyrgyzstan'},
  {
    label: "Lao People'S Democratic Republic",
    value: "Lao People'S Democratic Republic",
  },
  {label: 'Latvia', value: 'Latvia'},
  {label: 'Lebanon', value: 'Lebanon'},
  {label: 'Lesotho', value: 'Lesotho'},
  {label: 'Liberia', value: 'Liberia'},
  {label: 'Libyan Arab Jamahiriya', value: 'Libyan Arab Jamahiriya'},
  {label: 'Liechtenstein', value: 'Liechtenstein'},
  {label: 'Lithuania', value: 'Lithuania'},
  {label: 'Luxembourg', value: 'Luxembourg'},
  {label: 'Macao', value: 'Macao'},
  {
    label: 'Macedonia, The Former Yugoslav Republic of',
    value: 'Macedonia, The Former Yugoslav Republic of',
  },
  {label: 'Madagascar', value: 'Madagascar'},
  {label: 'Malawi', value: 'Malawi'},
  {label: 'Malaysia', value: 'Malaysia'},
  {label: 'Maldives', value: 'Maldives'},
  {label: 'Mali', value: 'Mali'},
  {label: 'Malta', value: 'Malta'},
  {label: 'Marshall Islands', value: 'Marshall Islands'},
  {label: 'Martinique', value: 'Martinique'},
  {label: 'Mauritania', value: 'Mauritania'},
  {label: 'Mauritius', value: 'Mauritius'},
  {label: 'Mayotte', value: 'Mayotte'},
  {label: 'Mexico', value: 'Mexico'},
  {
    label: 'Micronesia, Federated States of',
    value: 'Micronesia, Federated States of',
  },
  {label: 'Moldova, Republic of', value: 'Moldova, Republic of'},
  {label: 'Monaco', value: 'Monaco'},
  {label: 'Mongolia', value: 'Mongolia'},
  {label: 'Montserrat', value: 'Montserrat'},
  {label: 'Morocco', value: 'Morocco'},
  {label: 'Mozambique', value: 'Mozambique'},
  {label: 'Myanmar', value: 'Myanmar'},
  {label: 'Namibia', value: 'Namibia'},
  {label: 'Nauru', value: 'Nauru'},
  {label: 'Nepal', value: 'Nepal'},
  {label: 'Netherlands', value: 'Netherlands'},
  {label: 'Netherlands Antilles', value: 'Netherlands Antilles'},
  {label: 'New Caledonia', value: 'New Caledonia'},
  {label: 'New Zealand', value: 'New Zealand'},
  {label: 'Nicaragua', value: 'Nicaragua'},
  {label: 'Niger', value: 'Niger'},

  {label: 'Niue', value: 'Niue'},
  {label: 'Norfolk Island', value: 'Norfolk Island'},
  {
    label: 'Northern Mariana Islands',
    value: 'Northern Mariana Islands',
  },
  {label: 'Norway', value: 'Norway'},
  {label: 'Oman', value: 'Oman'},
  {label: 'Pakistan', value: 'Pakistan'},
  {label: 'Palau', value: 'Palau'},
  {
    label: 'Palestinian Territory, Occupied',
    value: 'Palestinian Territory, Occupied',
  },
  {label: 'Panama', value: 'Panama'},
  {label: 'Papua New Guinea', value: 'Papua New Guinea'},
  {label: 'Paraguay', value: 'Paraguay'},
  {label: 'Peru', value: 'Peru'},
  {label: 'Philippines', value: 'Philippines'},
  {label: 'Pitcairn', value: 'Pitcairn'},
  {label: 'Poland', value: 'Poland'},
  {label: 'Portugal', value: 'Portugal'},
  {label: 'Puerto Rico', value: 'Puerto Rico'},
  {label: 'Qatar', value: 'Qatar'},
  {label: 'Reunion', value: 'Reunion'},
  {label: 'Romania', value: 'Romania'},
  {label: 'Russian Federation', value: 'Russian Federation'},
  {label: 'RWANDA', value: 'RWANDA'},
  {label: 'Saint Helena', value: 'Saint Helena'},
  {label: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis'},
  {label: 'Saint Lucia', value: 'Saint Lucia'},
  {
    label: 'Saint Pierre and Miquelon',
    value: 'Saint Pierre and Miquelon',
  },
  {
    label: 'Saint Vincent and the Grenadines',
    value: 'Saint Vincent and the Grenadines',
  },
  {label: 'Samoa', value: 'Samoa'},
  {label: 'San Marino', value: 'San Marino'},
  {label: 'Sao Tome and Principe', value: 'Sao Tome and Principe'},
  {label: 'Saudi Arabia', value: 'Saudi Arabia'},
  {label: 'Senegal', value: 'Senegal'},
  {label: 'Serbia and Montenegro', value: 'Serbia and Montenegro'},
  {label: 'Seychelles', value: 'Seychelles'},
  {label: 'Sierra Leone', value: 'Sierra Leone'},
  {label: 'Singapore', value: 'Singapore'},
  {label: 'Slovakia', value: 'Slovakia'},
  {label: 'Slovenia', value: 'Slovenia'},
  {label: 'Solomon Islands', value: 'Solomon Islands'},
  {label: 'Somalia', value: 'Somalia'},
  {label: 'South Africa', value: 'South Africa'},
  {
    label: 'South Georgia and the South Sandwich Islands',
    value: 'South Georgia and the South Sandwich Islands',
  },
  {label: 'Spain', value: 'Spain'},
  {label: 'Sri Lanka', value: 'Sri Lanka'},
  {label: 'Sudan', value: 'Sudan'},
  {label: 'Suriname', value: 'Suriname'},
  {label: 'Svalbard and Jan Mayen', value: 'Svalbard and Jan Mayen'},
  {label: 'Swaziland', value: 'Swaziland'},
  {label: 'Sweden', value: 'Sweden'},
  {label: 'Switzerland', value: 'Switzerland'},
  {label: 'Syrian Arab Republic', value: 'Syrian Arab Republic'},
  {
    label: 'Taiwan, Province of China',
    value: 'Taiwan, Province of China',
  },
  {label: 'Tajikistan', value: 'Tajikistan'},
  {
    label: 'Tanzania, United Republic of',
    value: 'Tanzania, United Republic of',
  },
  {label: 'Thailand', value: 'Thailand'},
  {label: 'Timor-Leste', value: 'Timor-Leste'},
  {label: 'Togo', value: 'Togo'},
  {label: 'Tokelau', value: 'Tokelau'},
  {label: 'Tonga', value: 'Tonga'},
  {label: 'Trinidad and Tobago', value: 'Trinidad and Tobago'},
  {label: 'Tunisia', value: 'Tunisia'},
  {label: 'Turkey', value: 'Turkey'},
  {label: 'Turkmenistan', value: 'Turkmenistan'},
  {
    label: 'Turks and Caicos Islands',
    value: 'Turks and Caicos Islands',
  },
  {label: 'Tuvalu', value: 'Tuvalu'},
  {label: 'Uganda', value: 'Uganda'},
  {label: 'Ukraine', value: 'Ukraine'},
  {label: 'United Arab Emirates', value: 'United Arab Emirates'},
  {label: 'United Kingdom', value: 'United Kingdom'},
  {label: 'United States', value: 'United States'},
  {
    label: 'United States Minor Outlying Islands',
    value: 'United States Minor Outlying Islands',
  },
  {label: 'Uruguay', value: 'Uruguay'},
  {label: 'Uzbekistan', value: 'Uzbekistan'},
  {label: 'Vanuatu', value: 'Vanuatu'},
  {label: 'Venezuela', value: 'Venezuela'},
  {label: 'Viet Nam', value: 'Viet Nam'},
  {
    label: 'Virgin Islands, British',
    value: 'Virgin Islands, British',
  },
  {label: 'Virgin Islands, U.S.', value: 'Virgin Islands, U.S.'},
  {label: 'Wallis and Futuna', value: 'Wallis and Futuna'},
  {label: 'Western Sahara', value: 'Western Sahara'},
  {label: 'Yemen', value: 'Yemen'},
  {label: 'Zambia', value: 'Zambia'},
  {label: 'Zimbabwe', value: 'Zimbabwe'},
];

export const allCities = [
  {label: 'Aba South', value: 'Aba South'},
  {label: 'Arochukwu', value: 'Arochukwu'},
  {label: 'Bende', value: 'Bende'},
  {label: 'Ikwuano', value: 'Ikwuano'},
  {label: 'Isiala Ngwa North', value: 'Isiala Ngwa North'},
  {label: 'Isiala Ngwa South', value: 'Isiala Ngwa South'},
  {label: 'Isuikwuato', value: 'Isuikwuato'},
  {label: 'Obi Ngwa', value: 'Obi Ngwa'},
  {label: 'Ohafia', value: 'Ohafia'},
  {label: 'Osisioma', value: 'Osisioma'},
  {label: 'Ugwunagbo', value: 'Ugwunagbo'},
  {label: 'Ukwa East', value: 'Ukwa East'},
  {label: 'Ukwa West', value: 'Ukwa West'},
  {label: 'Umuahia North', value: 'Umuahia North'},
  {label: 'Umuahia South', value: 'Umuahia South'},
  {label: 'Umu Nneochi', value: 'Umu Nneochi'},
  {label: 'Fufure', value: 'Fufure'},
  {label: 'Ganye', value: 'Ganye'},
  {label: 'Gayuk', value: 'Gayuk'},
  {label: 'Gombi', value: 'Gombi'},
  {label: 'Grie', value: 'Grie'},
  {label: 'Hong', value: 'Hong'},
  {label: 'Jada', value: 'Jada'},
  {label: 'Lamurde', value: 'Lamurde'},
  {label: 'Madagali', value: 'Madagali'},
  {label: 'Maiha', value: 'Maiha'},
  {label: 'Mayo Belwa', value: 'Mayo Belwa'},
  {label: 'Michika', value: 'Michika'},
  {label: 'Mubi North', value: 'Mubi North'},
  {label: 'Mubi South', value: 'Mubi South'},
  {label: 'Numan', value: 'Numan'},
  {label: 'Shelleng', value: 'Shelleng'},
  {label: 'Song', value: 'Song'},
  {label: 'Toungo', value: 'Toungo'},
  {label: 'Yola North', value: 'Yola North'},
  {label: 'Yola South', value: 'Yola South'},
  {label: 'Eastern Obolo', value: 'Eastern Obolo'},
  {label: 'Eket', value: 'Eket'},
  {label: 'Esit Eket', value: 'Esit Eket'},
  {label: 'Essien Udim', value: 'Essien Udim'},
  {label: 'Etim Ekpo', value: 'Etim Ekpo'},
  {label: 'Etinan', value: 'Etinan'},
  {label: 'Ibeno', value: 'Ibeno'},
  {label: 'Ibesikpo Asutan', value: 'Ibesikpo Asutan'},
  {label: 'Ibiono-Ibom', value: 'Ibiono-Ibom'},
  {label: 'Ika', value: 'Ika'},
  {label: 'Ikono', value: 'Ikono'},
  {label: 'Ikot Abasi', value: 'Ikot Abasi'},
  {label: 'Ikot Ekpene', value: 'Ikot Ekpene'},
  {label: 'Ini', value: 'Ini'},
  {label: 'Itu', value: 'Itu'},
  {label: 'Mbo', value: 'Mbo'},
  {label: 'Mkpat-Enin', value: 'Mkpat-Enin'},
  {label: 'Nsit-Atai', value: 'Nsit-Atai'},
  {label: 'Nsit-Ibom', value: 'Nsit-Ibom'},
  {label: 'Nsit-Ubium', value: 'Nsit-Ubium'},
  {label: 'Obot Akara', value: 'Obot Akara'},
  {label: 'Okobo', value: 'Okobo'},
  {label: 'Onna', value: 'Onna'},
  {label: 'Oron', value: 'Oron'},
  {label: 'Oruk Anam', value: 'Oruk Anam'},
  {label: 'Udung-Uko', value: 'Udung-Uko'},
  {label: 'Ukanafun', value: 'Ukanafun'},
  {label: 'Uruan', value: 'Uruan'},
  {label: 'Urue-Offong/Oruko', value: 'Urue-Offong/Oruko'},
  {label: 'Uyo', value: 'Uyo'},
  {label: 'Anambra East', value: 'Anambra East'},
  {label: 'Anambra West', value: 'Anambra West'},
  {label: 'Anaocha', value: 'Anaocha'},
  {label: 'Awka North', value: 'Awka North'},
  {label: 'Awka South', value: 'Awka South'},
  {label: 'Ayamelum', value: 'Ayamelum'},
  {label: 'Dunukofia', value: 'Dunukofia'},
  {label: 'Ekwusigo', value: 'Ekwusigo'},
  {label: 'Idemili North', value: 'Idemili North'},
  {label: 'Idemili South', value: 'Idemili South'},
  {label: 'Ihiala', value: 'Ihiala'},
  {label: 'Njikoka', value: 'Njikoka'},
  {label: 'Nnewi North', value: 'Nnewi North'},
  {label: 'Nnewi South', value: 'Nnewi South'},
  {label: 'Ogbaru', value: 'Ogbaru'},
  {label: 'Onitsha North', value: 'Onitsha North'},
  {label: 'Onitsha South', value: 'Onitsha South'},
  {label: 'Orumba North', value: 'Orumba North'},
  {label: 'Orumba South', value: 'Orumba South'},
  {label: 'Oyi', value: 'Oyi'},
  {label: 'Bauchi', value: 'Bauchi'},
  {label: 'Bogoro', value: 'Bogoro'},
  {label: 'Damban', value: 'Damban'},
  {label: 'Darazo', value: 'Darazo'},
  {label: 'Dass', value: 'Dass'},
  {label: 'Gamawa', value: 'Gamawa'},
  {label: 'Ganjuwa', value: 'Ganjuwa'},
  {label: 'Giade', value: 'Giade'},
  {label: 'Itas/Gadau', value: 'Itas/Gadau'},
  {label: "Jama'are", value: "Jama'are"},
  {label: 'Katagum', value: 'Katagum'},
  {label: 'Kirfi', value: 'Kirfi'},
  {label: 'Misau', value: 'Misau'},
  {label: 'Ningi', value: 'Ningi'},
  {label: 'Shira', value: 'Shira'},
  {label: 'Tafawa Balewa', value: 'Tafawa Balewa'},
  {label: 'Toro', value: 'Toro'},
  {label: 'Warji', value: 'Warji'},
  {label: 'Zaki', value: 'Zaki'},
  {label: 'Ekeremor', value: 'Ekeremor'},
  {label: 'Kolokuma/Opokuma', value: 'Kolokuma/Opokuma'},
  {label: 'Nembe', value: 'Nembe'},
  {label: 'Ogbia', value: 'Ogbia'},
  {label: 'Sagbama', value: 'Sagbama'},
  {label: 'Southern Ijaw', value: 'Southern Ijaw'},
  {label: 'Yenagoa', value: 'Yenagoa'},
  {label: 'Apa', value: 'Apa'},
  {label: 'Ado', value: 'Ado'},
  {label: 'Buruku', value: 'Buruku'},
  {label: 'Gboko', value: 'Gboko'},
  {label: 'Guma', value: 'Guma'},
  {label: 'Gwer East', value: 'Gwer East'},
  {label: 'Gwer West', value: 'Gwer West'},
  {label: 'Katsina-Ala', value: 'Katsina-Ala'},
  {label: 'Konshisha', value: 'Konshisha'},
  {label: 'Kwande', value: 'Kwande'},
  {label: 'Logo', value: 'Logo'},
  {label: 'Makurdi', value: 'Makurdi'},
  {label: 'Obi', value: 'Obi'},
  {label: 'Ogbadibo', value: 'Ogbadibo'},
  {label: 'Ohimini', value: 'Ohimini'},
  {label: 'Oju', value: 'Oju'},
  {label: 'Okpokwu', value: 'Okpokwu'},
  {label: 'Oturkpo', value: 'Oturkpo'},
  {label: 'Tarka', value: 'Tarka'},
  {label: 'Ukum', value: 'Ukum'},
  {label: 'Ushongo', value: 'Ushongo'},
  {label: 'Vandeikya', value: 'Vandeikya'},
  {label: 'Askira/Uba', value: 'Askira/Uba'},
  {label: 'Bama', value: 'Bama'},
  {label: 'Bayo', value: 'Bayo'},
  {label: 'Biu', value: 'Biu'},
  {label: 'Chibok', value: 'Chibok'},
  {label: 'Damboa', value: 'Damboa'},
  {label: 'Dikwa', value: 'Dikwa'},
  {label: 'Gubio', value: 'Gubio'},
  {label: 'Guzamala', value: 'Guzamala'},
  {label: 'Gwoza', value: 'Gwoza'},
  {label: 'Hawul', value: 'Hawul'},
  {label: 'Jere', value: 'Jere'},
  {label: 'Kaga', value: 'Kaga'},
  {label: 'Kala/Balge', value: 'Kala/Balge'},
  {label: 'Konduga', value: 'Konduga'},
  {label: 'Kukawa', value: 'Kukawa'},
  {label: 'Kwaya Kusar', value: 'Kwaya Kusar'},
  {label: 'Mafa', value: 'Mafa'},
  {label: 'Magumeri', value: 'Magumeri'},
  {label: 'Maiduguri', value: 'Maiduguri'},
  {label: 'Marte', value: 'Marte'},
  {label: 'Mobbar', value: 'Mobbar'},
  {label: 'Monguno', value: 'Monguno'},
  {label: 'Ngala', value: 'Ngala'},
  {label: 'Nganzai', value: 'Nganzai'},
  {label: 'Shani', value: 'Shani'},
  {label: 'Akamkpa', value: 'Akamkpa'},
  {label: 'Akpabuyo', value: 'Akpabuyo'},
  {label: 'Bakassi', value: 'Bakassi'},
  {label: 'Bekwarra', value: 'Bekwarra'},
  {label: 'Biase', value: 'Biase'},
  {label: 'Boki', value: 'Boki'},
  {label: 'Calabar Municipal', value: 'Calabar Municipal'},
  {label: 'Calabar South', value: 'Calabar South'},
  {label: 'Etung', value: 'Etung'},
  {label: 'Ikom', value: 'Ikom'},
  {label: 'Obanliku', value: 'Obanliku'},
  {label: 'Obubra', value: 'Obubra'},
  {label: 'Obudu', value: 'Obudu'},
  {label: 'Odukpani', value: 'Odukpani'},
  {label: 'Ogoja', value: 'Ogoja'},
  {label: 'Yakuur', value: 'Yakuur'},
  {label: 'Yala', value: 'Yala'},
  {label: 'Aniocha South', value: 'Aniocha South'},
  {label: 'Bomadi', value: 'Bomadi'},
  {label: 'Burutu', value: 'Burutu'},
  {label: 'Ethiope East', value: 'Ethiope East'},
  {label: 'Ethiope West', value: 'Ethiope West'},
  {label: 'Ika North East', value: 'Ika North East'},
  {label: 'Ika South', value: 'Ika South'},
  {label: 'Isoko North', value: 'Isoko North'},
  {label: 'Isoko South', value: 'Isoko South'},
  {label: 'Ndokwa East', value: 'Ndokwa East'},
  {label: 'Ndokwa West', value: 'Ndokwa West'},
  {label: 'Okpe', value: 'Okpe'},
  {label: 'Oshimili North', value: 'Oshimili North'},
  {label: 'Oshimili South', value: 'Oshimili South'},
  {label: 'Patani', value: 'Patani'},
  {label: 'Sapele', value: 'Sapele'},
  {label: 'Udu', value: 'Udu'},
  {label: 'Ughelli North', value: 'Ughelli North'},
  {label: 'Ughelli South', value: 'Ughelli South'},
  {label: 'Ukwuani', value: 'Ukwuani'},
  {label: 'Uvwie', value: 'Uvwie'},
  {label: 'Warri North', value: 'Warri North'},
  {label: 'Warri South', value: 'Warri South'},
  {label: 'Warri South West', value: 'Warri South West'},
  {label: 'Afikpo North', value: 'Afikpo North'},
  {label: 'Afikpo South', value: 'Afikpo South'},
  {label: 'Ebonyi', value: 'Ebonyi'},
  {label: 'Ezza North', value: 'Ezza North'},
  {label: 'Ezza South', value: 'Ezza South'},
  {label: 'Ikwo', value: 'Ikwo'},
  {label: 'Ishielu', value: 'Ishielu'},
  {label: 'Ivo', value: 'Ivo'},
  {label: 'Izzi', value: 'Izzi'},
  {label: 'Ohaozara', value: 'Ohaozara'},
  {label: 'Ohaukwu', value: 'Ohaukwu'},
  {label: 'Onicha', value: 'Onicha'},
  {label: 'Egor', value: 'Egor'},
  {label: 'Esan Central', value: 'Esan Central'},
  {label: 'Esan North-East', value: 'Esan North-East'},
  {label: 'Esan South-East', value: 'Esan South-East'},
  {label: 'Esan West', value: 'Esan West'},
  {label: 'Etsako Central', value: 'Etsako Central'},
  {label: 'Etsako East', value: 'Etsako East'},
  {label: 'Etsako West', value: 'Etsako West'},
  {label: 'Igueben', value: 'Igueben'},
  {label: 'Ikpoba Okha', value: 'Ikpoba Okha'},
  {label: 'Orhionmwon', value: 'Orhionmwon'},
  {label: 'Oredo', value: 'Oredo'},
  {label: 'Ovia North-East', value: 'Ovia North-East'},
  {label: 'Ovia South-West', value: 'Ovia South-West'},
  {label: 'Owan East', value: 'Owan East'},
  {label: 'Owan West', value: 'Owan West'},
  {label: 'Uhunmwonde', value: 'Uhunmwonde'},
  {label: 'Efon', value: 'Efon'},
  {label: 'Ekiti East', value: 'Ekiti East'},
  {label: 'Ekiti South-West', value: 'Ekiti South-West'},
  {label: 'Ekiti West', value: 'Ekiti West'},
  {label: 'Emure', value: 'Emure'},
  {label: 'Gbonyin', value: 'Gbonyin'},
  {label: 'Ido Osi', value: 'Ido Osi'},
  {label: 'Ijero', value: 'Ijero'},
  {label: 'Ikere', value: 'Ikere'},
  {label: 'Ikole', value: 'Ikole'},
  {label: 'Ilejemeje', value: 'Ilejemeje'},
  {label: 'Irepodun/Ifelodun', value: 'Irepodun/Ifelodun'},
  {label: 'Ise/Orun', value: 'Ise/Orun'},
  {label: 'Moba', value: 'Moba'},
  {label: 'Oye', value: 'Oye'},
  {label: 'Awgu', value: 'Awgu'},
  {label: 'Enugu East', value: 'Enugu East'},
  {label: 'Enugu North', value: 'Enugu North'},
  {label: 'Enugu South', value: 'Enugu South'},
  {label: 'Ezeagu', value: 'Ezeagu'},
  {label: 'Igbo Etiti', value: 'Igbo Etiti'},
  {label: 'Igbo Eze North', value: 'Igbo Eze North'},
  {label: 'Igbo Eze South', value: 'Igbo Eze South'},
  {label: 'Isi Uzo', value: 'Isi Uzo'},
  {label: 'Nkanu East', value: 'Nkanu East'},
  {label: 'Nkanu West', value: 'Nkanu West'},
  {label: 'Nsukka', value: 'Nsukka'},
  {label: 'Oji River', value: 'Oji River'},
  {label: 'Udenu', value: 'Udenu'},
  {label: 'Udi', value: 'Udi'},
  {label: 'Uzo Uwani', value: 'Uzo Uwani'},
  {label: 'Bwari', value: 'Bwari'},
  {label: 'Gwagwalada', value: 'Gwagwalada'},
  {label: 'Kuje', value: 'Kuje'},
  {label: 'Kwali', value: 'Kwali'},
  {label: 'Municipal Area Council', value: 'Municipal Area Council'},
  {label: 'Balanga', value: 'Balanga'},
  {label: 'Billiri', value: 'Billiri'},
  {label: 'Dukku', value: 'Dukku'},
  {label: 'Funakaye', value: 'Funakaye'},
  {label: 'Gombe', value: 'Gombe'},
  {label: 'Kaltungo', value: 'Kaltungo'},
  {label: 'Kwami', value: 'Kwami'},
  {label: 'Nafada', value: 'Nafada'},
  {label: 'Shongom', value: 'Shongom'},
  {label: 'Yamaltu/Deba', value: 'Yamaltu/Deba'},
  {label: 'Ahiazu Mbaise', value: 'Ahiazu Mbaise'},
  {label: 'Ehime Mbano', value: 'Ehime Mbano'},
  {label: 'Ezinihitte', value: 'Ezinihitte'},
  {label: 'Ideato North', value: 'Ideato North'},
  {label: 'Ideato South', value: 'Ideato South'},
  {label: 'Ihitte/Uboma', value: 'Ihitte/Uboma'},
  {label: 'Ikeduru', value: 'Ikeduru'},
  {label: 'Isiala Mbano', value: 'Isiala Mbano'},
  {label: 'Isu', value: 'Isu'},
  {label: 'Mbaitoli', value: 'Mbaitoli'},
  {label: 'Ngor Okpala', value: 'Ngor Okpala'},
  {label: 'Njaba', value: 'Njaba'},
  {label: 'Nkwerre', value: 'Nkwerre'},
  {label: 'Nwangele', value: 'Nwangele'},
  {label: 'Obowo', value: 'Obowo'},
  {label: 'Oguta', value: 'Oguta'},
  {label: 'Ohaji/Egbema', value: 'Ohaji/Egbema'},
  {label: 'Okigwe', value: 'Okigwe'},
  {label: 'Orlu', value: 'Orlu'},
  {label: 'Orsu', value: 'Orsu'},
  {label: 'Oru East', value: 'Oru East'},
  {label: 'Oru West', value: 'Oru West'},
  {label: 'Owerri Municipal', value: 'Owerri Municipal'},
  {label: 'Owerri North', value: 'Owerri North'},
  {label: 'Danja', value: 'Danja'},
  {label: 'Dan Musa', value: 'Dan Musa'},
  {label: 'Daura', value: 'Daura'},
  {label: 'Dutsi', value: 'Dutsi'},
  {label: 'Dutsin Ma', value: 'Dutsin Ma'},
  {label: 'Faskari', value: 'Faskari'},
  {label: 'Funtua', value: 'Funtua'},
  {label: 'Ingawa', value: 'Ingawa'},
  {label: 'Jibia', value: 'Jibia'},
  {label: 'Kafur', value: 'Kafur'},
  {label: 'Kaita', value: 'Kaita'},
  {label: 'Kankara', value: 'Kankara'},
  {label: 'Kankia', value: 'Kankia'},
  {label: 'Katsina', value: 'Katsina'},
  {label: 'Kurfi', value: 'Kurfi'},
  {label: 'Kusada', value: 'Kusada'},
  {label: "Mai'Adua", value: "Mai'Adua"},
  {label: 'Malumfashi', value: 'Malumfashi'},
  {label: 'Mani', value: 'Mani'},
  {label: 'Mashi', value: 'Mashi'},
  {label: 'Matazu', value: 'Matazu'},
  {label: 'Musawa', value: 'Musawa'},
  {label: 'Rimi', value: 'Rimi'},
  {label: 'Sabuwa', value: 'Sabuwa'},
  {label: 'Safana', value: 'Safana'},
  {label: 'Sandamu', value: 'Sandamu'},
  {label: 'Zango', value: 'Zango'},
  {label: 'Arewa Dandi', value: 'Arewa Dandi'},
  {label: 'Argungu', value: 'Argungu'},
  {label: 'Augie', value: 'Augie'},
  {label: 'Bagudo', value: 'Bagudo'},
  {label: 'Birnin Kebbi', value: 'Birnin Kebbi'},
  {label: 'Bunza', value: 'Bunza'},
  {label: 'Dandi', value: 'Dandi'},
  {label: 'Fakai', value: 'Fakai'},
  {label: 'Gwandu', value: 'Gwandu'},
  {label: 'Jega', value: 'Jega'},
  {label: 'Kalgo', value: 'Kalgo'},
  {label: 'Koko/Besse', value: 'Koko/Besse'},
  {label: 'Maiyama', value: 'Maiyama'},
  {label: 'Ngaski', value: 'Ngaski'},
  {label: 'Sakaba', value: 'Sakaba'},
  {label: 'Shanga', value: 'Shanga'},
  {label: 'Suru', value: 'Suru'},
  {label: 'Wasagu/Danko', value: 'Wasagu/Danko'},
  {label: 'Yauri', value: 'Yauri'},
  {label: 'Zuru', value: 'Zuru'},
  {label: 'Ajaokuta', value: 'Ajaokuta'},
  {label: 'Ankpa', value: 'Ankpa'},
  {label: 'Bassa', value: 'Bassa'},
  {label: 'Dekina', value: 'Dekina'},
  {label: 'Ibaji', value: 'Ibaji'},
  {label: 'Idah', value: 'Idah'},
  {label: 'Igalamela Odolu', value: 'Igalamela Odolu'},
  {label: 'Ijumu', value: 'Ijumu'},
  {label: 'Kabba/Bunu', value: 'Kabba/Bunu'},
  {label: 'Kogi', value: 'Kogi'},
  {label: 'Lokoja', value: 'Lokoja'},
  {label: 'Mopa Muro', value: 'Mopa Muro'},
  {label: 'Ofu', value: 'Ofu'},
  {label: 'Ogori/Magongo', value: 'Ogori/Magongo'},
  {label: 'Okehi', value: 'Okehi'},
  {label: 'Okene', value: 'Okene'},
  {label: 'Olamaboro', value: 'Olamaboro'},
  {label: 'Omala', value: 'Omala'},
  {label: 'Yagba East', value: 'Yagba East'},
  {label: 'Yagba West', value: 'Yagba West'},
  {label: 'Baruten', value: 'Baruten'},
  {label: 'Edu', value: 'Edu'},
  {label: 'Ekiti', value: 'Ekiti'},
  {label: 'Ifelodun', value: 'Ifelodun'},
  {label: 'Ilorin East', value: 'Ilorin East'},
  {label: 'Ilorin South', value: 'Ilorin South'},
  {label: 'Ilorin West', value: 'Ilorin West'},
  {label: 'Irepodun', value: 'Irepodun'},
  {label: 'Isin', value: 'Isin'},
  {label: 'Kaiama', value: 'Kaiama'},
  {label: 'Moro', value: 'Moro'},
  {label: 'Offa', value: 'Offa'},
  {label: 'Oke Ero', value: 'Oke Ero'},
  {label: 'Oyun', value: 'Oyun'},
  {label: 'Pategi', value: 'Pategi'},
  {label: 'Ajeromi-Ifelodun', value: 'Ajeromi-Ifelodun'},
  {label: 'Alimosho', value: 'Alimosho'},
  {label: 'Amuwo-Odofin', value: 'Amuwo-Odofin'},
  {label: 'Apapa', value: 'Apapa'},
  {label: 'Badagry', value: 'Badagry'},
  {label: 'Epe', value: 'Epe'},
  {label: 'Eti Osa', value: 'Eti Osa'},
  {label: 'Ibeju-Lekki', value: 'Ibeju-Lekki'},
  {label: 'Ifako-Ijaiye', value: 'Ifako-Ijaiye'},
  {label: 'Ikeja', value: 'Ikeja'},
  {label: 'Ikorodu', value: 'Ikorodu'},
  {label: 'Kosofe', value: 'Kosofe'},
  {label: 'Lagos Island', value: 'Lagos Island'},
  {label: 'Lagos Mainland', value: 'Lagos Mainland'},
  {label: 'Mushin', value: 'Mushin'},
  {label: 'Ojo', value: 'Ojo'},
  {label: 'Oshodi-Isolo', value: 'Oshodi-Isolo'},
  {label: 'Shomolu', value: 'Shomolu'},
  {label: 'Surulere', value: 'Surulere'},
  {label: 'Awe', value: 'Awe'},
  {label: 'Doma', value: 'Doma'},
  {label: 'Karu', value: 'Karu'},
  {label: 'Keana', value: 'Keana'},
  {label: 'Keffi', value: 'Keffi'},
  {label: 'Kokona', value: 'Kokona'},
  {label: 'Lafia', value: 'Lafia'},
  {label: 'Nasarawa', value: 'Nasarawa'},
  {label: 'Nasarawa Egon', value: 'Nasarawa Egon'},
  {label: 'Obi', value: 'Obi'},
  {label: 'Toto', value: 'Toto'},
  {label: 'Wamba', value: 'Wamba'},
  {label: 'Agwara', value: 'Agwara'},
  {label: 'Bida', value: 'Bida'},
  {label: 'Borgu', value: 'Borgu'},
  {label: 'Bosso', value: 'Bosso'},
  {label: 'Chanchaga', value: 'Chanchaga'},
  {label: 'Edati', value: 'Edati'},
  {label: 'Gbako', value: 'Gbako'},
  {label: 'Gurara', value: 'Gurara'},
  {label: 'Katcha', value: 'Katcha'},
  {label: 'Kontagora', value: 'Kontagora'},
  {label: 'Lapai', value: 'Lapai'},
  {label: 'Lavun', value: 'Lavun'},
  {label: 'Magama', value: 'Magama'},
  {label: 'Mariga', value: 'Mariga'},
  {label: 'Mashegu', value: 'Mashegu'},
  {label: 'Mokwa', value: 'Mokwa'},
  {label: 'Moya', value: 'Moya'},
  {label: 'Paikoro', value: 'Paikoro'},
  {label: 'Rafi', value: 'Rafi'},
  {label: 'Rijau', value: 'Rijau'},
  {label: 'Shiroro', value: 'Shiroro'},
  {label: 'Suleja', value: 'Suleja'},
  {label: 'Tafa', value: 'Tafa'},
  {label: 'Wushishi', value: 'Wushishi'},
  {label: 'Abeokuta South', value: 'Abeokuta South'},
  {label: 'Ado-Odo/Ota', value: 'Ado-Odo/Ota'},
  {label: 'Egbado North', value: 'Egbado North'},
  {label: 'Egbado South', value: 'Egbado South'},
  {label: 'Ewekoro', value: 'Ewekoro'},
  {label: 'Ifo', value: 'Ifo'},
  {label: 'Ijebu East', value: 'Ijebu East'},
  {label: 'Ijebu North', value: 'Ijebu North'},
  {label: 'Ijebu North East', value: 'Ijebu North East'},
  {label: 'Ijebu Ode', value: 'Ijebu Ode'},
  {label: 'Ikenne', value: 'Ikenne'},
  {label: 'Imeko Afon', value: 'Imeko Afon'},
  {label: 'Ipokia', value: 'Ipokia'},
  {label: 'Obafemi Owode', value: 'Obafemi Owode'},
  {label: 'Odeda', value: 'Odeda'},
  {label: 'Odogbolu', value: 'Odogbolu'},
  {label: 'Ogun Waterside', value: 'Ogun Waterside'},
  {label: 'Remo North', value: 'Remo North'},
  {label: 'Shagamu', value: 'Shagamu'},
  {label: 'Akoko North-West', value: 'Akoko North-West'},
  {label: 'Akoko South-West', value: 'Akoko South-West'},
  {label: 'Akoko South-East', value: 'Akoko South-East'},
  {label: 'Akure North', value: 'Akure North'},
  {label: 'Akure South', value: 'Akure South'},
  {label: 'Ese Odo', value: 'Ese Odo'},
  {label: 'Idanre', value: 'Idanre'},
  {label: 'Ifedore', value: 'Ifedore'},
  {label: 'Ilaje', value: 'Ilaje'},
  {label: 'Ile Oluji/Okeigbo', value: 'Ile Oluji/Okeigbo'},
  {label: 'Irele', value: 'Irele'},
  {label: 'Odigbo', value: 'Odigbo'},
  {label: 'Okitipupa', value: 'Okitipupa'},
  {label: 'Ondo East', value: 'Ondo East'},
  {label: 'Ondo West', value: 'Ondo West'},
  {label: 'Ose', value: 'Ose'},
  {label: 'Owo', value: 'Owo'},
  {label: 'Atakunmosa West', value: 'Atakunmosa West'},
  {label: 'Aiyedaade', value: 'Aiyedaade'},
  {label: 'Aiyedire', value: 'Aiyedire'},
  {label: 'Boluwaduro', value: 'Boluwaduro'},
  {label: 'Boripe', value: 'Boripe'},
  {label: 'Ede North', value: 'Ede North'},
  {label: 'Ede South', value: 'Ede South'},
  {label: 'Ife Central', value: 'Ife Central'},
  {label: 'Ife East', value: 'Ife East'},
  {label: 'Ife North', value: 'Ife North'},
  {label: 'Ife South', value: 'Ife South'},
  {label: 'Egbedore', value: 'Egbedore'},
  {label: 'Ejigbo', value: 'Ejigbo'},
  {label: 'Ifedayo', value: 'Ifedayo'},
  {label: 'Ifelodun', value: 'Ifelodun'},
  {label: 'Ila', value: 'Ila'},
  {label: 'Ilesa East', value: 'Ilesa East'},
  {label: 'Ilesa West', value: 'Ilesa West'},
  {label: 'Irepodun', value: 'Irepodun'},
  {label: 'Irewole', value: 'Irewole'},
  {label: 'Isokan', value: 'Isokan'},
  {label: 'Iwo', value: 'Iwo'},
  {label: 'Obokun', value: 'Obokun'},
  {label: 'Odo Otin', value: 'Odo Otin'},
  {label: 'Ola Oluwa', value: 'Ola Oluwa'},
  {label: 'Olorunda', value: 'Olorunda'},
  {label: 'Oriade', value: 'Oriade'},
  {label: 'Oriade', value: 'Oriade'},
  {label: 'Orolu', value: 'Orolu'},
  {label: 'Osogbo', value: 'Osogbo'},
  {label: 'Akinyele', value: 'Akinyele'},
  {label: 'Atiba', value: 'Atiba'},
  {label: 'Atisbo', value: 'Atisbo'},
  {label: 'Egbeda', value: 'Egbeda'},
  {label: 'Ibadan North', value: 'Ibadan North'},
  {label: 'Ibadan North-East', value: 'Ibadan North-East'},
  {label: 'Ibadan North-West', value: 'Ibadan North-West'},
  {label: 'Ibadan South-East', value: 'Ibadan South-East'},
  {label: 'Ibadan South-West', value: 'Ibadan South-West'},
  {label: 'Ibarapa Central', value: 'Ibarapa Central'},
  {label: 'Ibarapa East', value: 'Ibarapa East'},
  {label: 'Ibarapa North', value: 'Ibarapa North'},
  {label: 'Ido', value: 'Ido'},
  {label: 'Irepo', value: 'Irepo'},
  {label: 'Iseyin', value: 'Iseyin'},
  {label: 'Itesiwaju', value: 'Itesiwaju'},
  {label: 'Iwajowa', value: 'Iwajowa'},
  {label: 'Kajola', value: 'Kajola'},
  {label: 'Lagelu', value: 'Lagelu'},
  {label: 'Ogbomosho North', value: 'Ogbomosho North'},
  {label: 'Ogbomosho South', value: 'Ogbomosho South'},
  {label: 'Ogo Oluwa', value: 'Ogo Oluwa'},
  {label: 'Olorunsogo', value: 'Olorunsogo'},
  {label: 'Oluyole', value: 'Oluyole'},
  {label: 'Ona Ara', value: 'Ona Ara'},
  {label: 'Orelope', value: 'Orelope'},
  {label: 'Ori Ire', value: 'Ori Ire'},
  {label: 'Oyo', value: 'Oyo'},
  {label: 'Oyo East', value: 'Oyo East'},
  {label: 'Saki East', value: 'Saki East'},
  {label: 'Saki West', value: 'Saki West'},
  {label: 'Surulere', value: 'Surulere'},
  {label: 'Barkin Ladi', value: 'Barkin Ladi'},
  {label: 'Bassa', value: 'Bassa'},
  {label: 'Jos East', value: 'Jos East'},
  {label: 'Jos North', value: 'Jos North'},
  {label: 'Jos South', value: 'Jos South'},
  {label: 'Kanam', value: 'Kanam'},
  {label: 'Kanke', value: 'Kanke'},
  {label: 'Langtang South', value: 'Langtang South'},
  {label: 'Langtang North', value: 'Langtang North'},
  {label: 'Mangu', value: 'Mangu'},
  {label: 'Mikang', value: 'Mikang'},
  {label: 'Pankshin', value: 'Pankshin'},
  {label: "Qua'an Pan", value: "Qua'an Pan"},
  {label: 'Riyom', value: 'Riyom'},
  {label: 'Shendam', value: 'Shendam'},
  {label: 'Wase', value: 'Wase'},
  {label: 'Ahoada East', value: 'Ahoada East'},
  {label: 'Ahoada West', value: 'Ahoada West'},
  {label: 'Akuku-Toru', value: 'Akuku-Toru'},
  {label: 'Andoni', value: 'Andoni'},
  {label: 'Asari-Toru', value: 'Asari-Toru'},
  {label: 'Bonny', value: 'Bonny'},
  {label: 'Degema', value: 'Degema'},
  {label: 'Eleme', value: 'Eleme'},
  {label: 'Emuoha', value: 'Emuoha'},
  {label: 'Etche', value: 'Etche'},
  {label: 'Gokana', value: 'Gokana'},
  {label: 'Ikwerre', value: 'Ikwerre'},
  {label: 'Khana', value: 'Khana'},
  {label: 'Obio/Akpor', value: 'Obio/Akpor'},
  {label: 'Ogba/Egbema/Ndoni', value: 'Ogba/Egbema/Ndoni'},
  {label: 'Ogu/Bolo', value: 'Ogu/Bolo'},
  {label: 'Okrika', value: 'Okrika'},
  {label: 'Omuma', value: 'Omuma'},
  {label: 'Opobo/Nkoro', value: 'Opobo/Nkoro'},
  {label: 'Oyigbo', value: 'Oyigbo'},
  {label: 'Port Harcourt', value: 'Port Harcourt'},
  {label: 'Tai', value: 'Tai'},
  {label: 'Bodinga', value: 'Bodinga'},
  {label: 'Dange Shuni', value: 'Dange Shuni'},
  {label: 'Gada', value: 'Gada'},
  {label: 'Goronyo', value: 'Goronyo'},
  {label: 'Gudu', value: 'Gudu'},
  {label: 'Gwadabawa', value: 'Gwadabawa'},
  {label: 'Illela', value: 'Illela'},
  {label: 'Isa', value: 'Isa'},
  {label: 'Kebbe', value: 'Kebbe'},
  {label: 'Kware', value: 'Kware'},
  {label: 'Rabah', value: 'Rabah'},
  {label: 'Sabon Birni', value: 'Sabon Birni'},
  {label: 'Shagari', value: 'Shagari'},
  {label: 'Silame', value: 'Silame'},
  {label: 'Sokoto North', value: 'Sokoto North'},
  {label: 'Sokoto South', value: 'Sokoto South'},
  {label: 'Tambuwal', value: 'Tambuwal'},
  {label: 'Tangaza', value: 'Tangaza'},
  {label: 'Tureta', value: 'Tureta'},
  {label: 'Wamako', value: 'Wamako'},
  {label: 'Wurno', value: 'Wurno'},
  {label: 'Yabo', value: 'Yabo'},
  {label: 'Bali', value: 'Bali'},
  {label: 'Donga', value: 'Donga'},
  {label: 'Gashaka', value: 'Gashaka'},
  {label: 'Gassol', value: 'Gassol'},
  {label: 'Ibi', value: 'Ibi'},
  {label: 'Ibi', value: 'Ibi'},
  {label: 'Jalingo', value: 'Jalingo'},
  {label: 'Karim Lamido', value: 'Karim Lamido'},
  {label: 'Kumi', value: 'Kumi'},
  {label: 'Lau', value: 'Lau'},
  {label: 'Sardauna', value: 'Sardauna'},
  {label: 'Takum', value: 'Takum'},
  {label: 'Ussa', value: 'Ussa'},
  {label: 'Wukari', value: 'Wukari'},
  {label: 'Yorro', value: 'Yorro'},
  {label: 'Zing', value: 'Zing'},
  {label: 'Bursari', value: 'Bursari'},
  {label: 'Damaturu', value: 'Damaturu'},
  {label: 'Fika', value: 'Fika'},
  {label: 'Fune', value: 'Fune'},
  {label: 'Geidam', value: 'Geidam'},
  {label: 'Gujba', value: 'Gujba'},
  {label: 'Gulani', value: 'Gulani'},
  {label: 'Jakusko', value: 'Jakusko'},
  {label: 'Karasuwa', value: 'Karasuwa'},
  {label: 'Machina', value: 'Machina'},
  {label: 'Nangere', value: 'Nangere'},
  {label: 'Nguru', value: 'Nguru'},
  {label: 'Potiskum', value: 'Potiskum'},
  {label: 'Tarmuwa', value: 'Tarmuwa'},
  {label: 'Yunusari', value: 'Yunusari'},
  {label: 'Yusufari', value: 'Yusufari'},
  {label: 'Bakura', value: 'Bakura'},
  {label: 'Birnin Magaji/Kiyaw', value: 'Birnin Magaji/Kiyaw'},
  {label: 'Bukkuyum', value: 'Bukkuyum'},
  {label: 'Bungudu', value: 'Bungudu'},
  {label: 'Gummi', value: 'Gummi'},
  {label: 'Gusau', value: 'Gusau'},
  {label: 'Kaura Namoda', value: 'Kaura Namoda'},
  {label: 'Maradun', value: 'Maradun'},
  {label: 'Maru', value: 'Maru'},
  {label: 'Shinkafi', value: 'Shinkafi'},
  {label: 'Talata Mafara', value: 'Talata Mafara'},
  {label: 'Chafe', value: 'Chafe'},
  {label: 'Zurmi', value: 'Zurmi'},
];

export const allState = [
  {label: 'Lagos', value: 'Lagos'},
  {label: 'FCT - Abuja', value: 'FCT - Abuja'},
  {label: 'Kano', value: 'Kano'},
  {label: 'Rivers', value: 'Rivers'},
  //lagos
  //port harcourt
  //kano
  //abuja
  // { label: 'Abia', value: 'Abia' },
  // { label: 'Adamawa', value: 'Adamawa' },
  // { label: 'Akwa Ibom', value: 'Akwa Ibom' },
  // { label: 'Anambra', value: 'Anambra' },
  // { label: 'Bauchi', value: 'Bauchi' },
  // { label: 'Bayelsa', value: 'Bayelsa' },
  // { label: 'Benue', value: 'Benue' },
  // { label: 'Borno', value: 'Borno' },
  // { label: 'Cross River', value: 'Cross River' },
  // { label: 'Delta', value: 'Delta' },
  // { label: 'Ebonyi', value: 'Ebonyi' },
  // { label: 'Edo', value: 'Edo' },
  // { label: 'Ekiti', value: 'Ekiti' },
  // { label: 'Enugu', value: 'Enugu' },
  // { label: 'Gombe', value: 'Gombe' },
  // { label: 'Imo', value: 'Imo' },
  // { label: 'Jigawa', value: 'Jigawa' },
  // { label: 'Kaduna', value: 'Kaduna' },
  // { label: 'Katsina', value: 'Katsina' },
  // { label: 'Kebbi', value: 'Kebbi' },
  // { label: 'Kogi', value: 'Kogi' },
  // { label: 'Kwara', value: 'Kwara' },
  // { label: 'Nasarawa', value: 'Nasarawa' },
  // { label: 'Niger', value: 'Niger' },
  // { label: 'Ogun', value: 'Ogun' },
  // { label: 'Ondo', value: 'Ondo' },
  // { label: 'Osun', value: 'Osun' },
  // { label: 'Oyo', value: 'Oyo' },
  // { label: 'Plateau', value: 'Plateau' },
  // { label: 'Sokoto', value: 'Sokoto' },
  // { label: 'Taraba', value: 'Taraba' },
  // { label: 'Yobe', value: 'Yobe' },
  // { label: 'Zamfara', value: 'Zamfara' }
];
